-- 6강에서 만든 테이블에 이어서 실행
INSERT INTO EMP_T VALUES (104, '춘식이', NULL); -- 부서가 없는 신입사원
INSERT INTO DEPT_T VALUES (30, '디자인팀'); -- 사원이 없는 신설부서

COMMIT;

SELECT * FROM EMP_T;
SELECT * FROM DEPT_T;

SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_ID, D.DEPT_NAME
FROM EMP_T E
LEFT OUTER JOIN DEPT_T D
ON E.DEPT_ID = D.DEPT_ID
;

SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_ID, D.DEPT_NAME
FROM EMP_T E
RIGHT OUTER JOIN DEPT_T D
ON E.DEPT_ID = D.DEPT_ID
;

SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_ID, D.DEPT_NAME
FROM EMP_T E
FULL OUTER JOIN DEPT_T D
ON E.DEPT_ID = D.DEPT_ID
;


SELECT u.user_id, u.username, p.post_id, p.content
FROM USERS u
LEFT OUTER JOIN POSTS p 
ON u.user_id = p.user_id
ORDER BY u.user_id
;


SELECT u.user_id, u.username, p.post_id, p.content
FROM USERS u, POSTS p 
WHERE u.user_id = p.user_id (+)
ORDER BY u.user_id
;

SELECT E.EMP_NAME, D.DEPT_NAME 
FROM EMP_T E
CROSS JOIN DEPT_T D
;

SELECT E.EMP_NAME, D.DEPT_NAME 
FROM EMP_T E, DEPT_T D
;

-- 연습문제 1
SELECT P.POST_ID, P.CONTENT
FROM POSTS P
LEFT JOIN LIKES L
ON P.POST_ID = L.POST_ID
WHERE L.CREATION_DATE IS NULL
ORDER BY P.POST_ID
;


-- 연습문제 2
SELECT P.POST_ID, P.CONTENT, U.USERNAME
FROM POSTS P
LEFT JOIN COMMENTS C
ON P.POST_ID = C.POST_ID
INNER JOIN USERS U
ON P.USER_ID = U.USER_ID
WHERE C.COMMENT_TEXT IS NULL
ORDER BY POST_ID
;